[package]
name = "mnger-preon"
version = "0.1.0"
edition = "2021"


[dependencies]
# Spec Generation
schemars = "0.8.16"
revolt_okapi = { git = "https://github.com/0xlaguna/okapi.git", branch = "master" }
revolt_rocket_okapi = { git = "https://github.com/0xlaguna/okapi.git", branch = "master", features = ["swagger"] }

once_cell = "1.9.0"

# Async
futures = "0.3.30"
deadqueue = "0.2.4"
async-trait = "0.1.77"
async-recursion = "1.0.5"
async-std = { version = "1.12.0", features = ["attributes"], optional = true }