[package]
name = "mnger-api"
version = "0.1.0"
authors = ["Maykol Laguna <lagunamichael2@outlook.com>"]
edition = "2021"
publish = false

[dependencies]
async-stream = { version = "0.3.5" }
async-trait = { version = "0.1.73" }
futures = { version = "0.3.28" }
futures-util = { version = "0.3.28" }
rocket = { version = "=0.5.0", features = ["json"] }
serde_json = { version = "1.0.107" }
tokio = "1.32.0"
dotenvy = "0.15"

[dependencies.sea-orm-rocket]
version = "0.5.2"
features = ["rocket_okapi"]

[dependencies.rocket_okapi]
git = "https://github.com/GREsau/okapi.git"
branch = "master"
features = ["swagger", "rapidoc","rocket_db_pools"]

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["handlebars", "tera"]

[dependencies.rocket_cors]
git = "https://github.com/lawliet89/rocket_cors.git"
rev = "54fae070"
default-features = false